Feature/forms
olehhladkov/reactjs-gmp pull request #5
Opened 2023-03-15 16:24 UTC by olehhladkov

2023-03-27 11:16 UTC, Vladlan requested changes
![Screenshot 2023-03-27 at 11 58 14](https://user-images.githubusercontent.com/20605638/227924813-61f1b2f7-ad11-46f0-9c7e-6b546167a54b.png)

Add form validation like on a MoviesAPI.  Make multiple selection and date input properly.

2023-03-27 11:16 UTC, Vladlan commented on src/api/deleteMovie.js
> +export default async (id) => {
For development/debugging purposes it is better to have a name for a function (imagine you have code base without function names.

2023-03-27 11:16 UTC, Vladlan commented on src/components/MoviesModal.js
> +    onClose();
Add another argument in MoviesModal for onMovieDelete. Reason: onMovie close we should invoke onClose callback, on movie delete - onMovieDelete callback

2023-03-27 11:16 UTC, Vladlan commented on src/components/MovieForm.js
> +            type="text"
For date use type "date" https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

2023-03-27 11:16 UTC, Vladlan commented on src/components/MovieForm.js
> +            {genreOptions.map((genre) => (
Did you try to make multiple selection with this?

2023-03-27 15:16 UTC, olehhladkov commented on src/components/MovieForm.js
> +            {genreOptions.map((genre) => (
Yes, the screenshot is attached. 
<img width="703" alt="Screenshot 2023-03-27 at 17 05 58" src="https://user-images.githubusercontent.com/102797149/227984636-49436c1b-c944-4a9f-a4df-ac031b80d945.png">

2023-03-28 11:23 UTC, Vladlan approved these changes
I hope you will not use such multiple select (as you've implemented it in this PR) at production projects, and even in your own projects. But requirements are met.

2023-03-29 11:18 UTC, merged